server:
  port: 8081

spring:
  freemarker:
    expose-request-attributes: true
  datasource:
    url: jdbc:postgresql://localhost:5432/m3bankdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true