<#import '../parts/common.ftlh' as c>
<@c.page>
    <div class="container mt-5">
        <div class="alert alert-warning text-center">
            <h1 class="display-4">404</h1>
            <p class="lead">Страница не найдена</p>
            <hr class="my-4">
            <p>К сожалению, запрашиваемая вами страница не существует или была удалена.</p>
            <a class="btn btn-primary" href="http://localhost:8081/home" role="button">На главную</a>
        </div>
    </div>
</@c.page>
